### ISSUE TITLE
Could not create WasmInstance, wasi_snapshot_preview1::fd_write has not been defined

### ISSUE THREAD

**Issue by jyfcrw** [LimeChain/matchstick#272]
I am trying to write test for my subgraph in my open source project [Kick-Ass NFT](https://github.com/jyfcrw/kick-nft/tree/subgraph), and when I execute **graph test** command under the path **kick-nft/packages/subgraph**, it was failed with the following error:

````
thread 'main' panicked at '🆘 Could not create WasmInstance from valid module with context: unknown import: `wasi_snapshot_preview1::fd_write` has not been defined', src/instance.rs:99:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_display
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   3: matchstick::instance::MatchstickInstance<C>::new::{{closure}}
             at /home/uxx/Work/matchstick/src/instance.rs:99:13
   4: core::result::Result<T,E>::unwrap_or_else
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1082:23
   5: matchstick::instance::MatchstickInstance<C>::new
             at /home/uxx/Work/matchstick/src/instance.rs:86:9
   6: matchstick::main::{{closure}}
             at /home/uxx/Work/matchstick/src/main.rs:257:33
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:84:28
   8: core::iter::traits::iterator::Iterator::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:2171:21
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:124:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:737:9
  11: <hashbrown::map::HashMap<K,V,S,A> as core::iter::traits::collect::Extend<(K,V)>>::extend
             at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/map.rs:3404:9
  12: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::Extend<(K,V)>>::extend
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/collections/hash/map.rs:2826:9
  13: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/collections/hash/map.rs:2811:9
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1745:9
  15: matchstick::main
             at /home/uxx/Work/matchstick/src/main.rs:255:68
  16: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
````

Node.js v14.18.2
yarn 1.22.17
npm 6.14.15
Ubuntu 20.04.3 LTS
graph-cli 0.25.1
Matchstick 0.2.3

I also tried compiling matchstick manully, as well as docker, they all have the same error.

I am new to rust lang, I read the source code roughly, noticed graph-node and matchstick all use wasmtime(0.27.0) as WASM runtime, I found wasi_snapshot_preview1 is defined in AssemblyScript, I faild to find the exact reason. Looking forward to your help, thanks a lot!

**Comment by dimitrovmaksim** [comment]
`console.log` does not work with AssemblyScript, you should use the logging API instead https://thegraph.com/docs/en/developer/assemblyscript-api#logging-api

Also the `runTests()` function is not required anymore https://github.com/jyfcrw/kick-nft/blob/subgraph/packages/subgraph/tests/tradeStatus.test.ts#L8

**Comment by jyfcrw** [comment]
@dimitrovmaksim Thanks very much, I made corrections according to your demo-subgraph, now it works.
